### ISSUE TITLE
set custom type for inpustream parameters of request

### ISSUE THREAD

**Issue by itulau** [darkxanter/ktor-openapi-generator#2]
As the name suggest, I was wondering if it could be possible to set the type for inputstream parameters of request to be other than "string($binary)". 
I was thinking something like the content type if present, like application/pdf.
I know "string($binary)" is technically correct, but I don't feel it's sufficiently descriptive of the actual expected type of the file, if any.
![Screenshot from 2024-12-12 16-34-53](https://github.com/user-attachments/assets/5aa5b18f-1451-4e75-b5ec-50dac7dbc9e3)

**Comment by darkxanter** [comment]
If you want to view the spec using swagger ui, you can't get away from string($binary).
But the OpenAPI 3.1.0 spec mentions an additional contentMediaType field, where you can specify the content type.
https://spec.openapis.org/oas/v3.1.0.html#considerations-for-file-uploads
```yaml
requestBody:
  content:
    multipart/form-data:
      schema:
        type: object
        properties:
          file:
            type: string
            format: binary
            contentMediaType: application/pdf
```
In swagger ui it will look like this:
![image](https://github.com/user-attachments/assets/f8f3cb0b-8001-4dfb-beda-0efafd25e0be)

**Comment by itulau** [comment]
Hi, thank you for your quick response.

> If you want to view the spec using swagger ui, you can't get away from string($binary).

Can't this be controlled by code when generating the specification? So instead of writing "string" or "binary" we could theoretically write whatever we want given a configuration, like the content type?

So the specification could end up with something like "application/pdf(binary)" instead of "string(binary)"

**Comment by darkxanter** [comment]
If you do this:
```
requestBody:
  content:
    multipart/form-data:
      schema:
        type: object
        properties:
          file:
            type: application/pdf
            format: binary
```
This will break the Swagger UI:
![image](https://github.com/user-attachments/assets/226c8226-3b18-4e2a-995a-7b174333d95c)

[Swagger UI not yet support 3.1.0 for file uploads](https://github.com/swagger-api/swagger-ui/issues/9278)

I don't want to add anything that isn't described in the OpenAPI spec.
But I can support version 3.1.0.

**Comment by itulau** [comment]
> This will break the Swagger UI:
 
 Ok, I wasn't aware of that. Thank you for the heads up.

> I don't want to add anything that isn't described in the OpenAPI spec.

Yeah that's very reasonable. 
I didn't know it would break Swagger UI, but I was expecting a way to expose the content type of the parameter of the request body, but it seems it's not possible on their end yet.

Thank you.
